# This is a workflow to deploy the react code to GitHub Pages.
name: Deploy to Uberspace via GitHub Pages

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build and Deploy
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          check-latest: true
          cache: 'npm'
      - name: Install Dependencies
        run: yarn
      - name: Add gh-pages as a dev-dependency
        run: yarn add --dev gh-pages
      - name: Build ReactJS App
        run: yarn build
      - name: Remove node_modules folder
        run: rm -rf node_modules
      - name: Deploy to GitHub Pages
        uses: Cecilapp/GitHub-Pages-deploy@3.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          email: thomas.rosen@me.com
          build_dir: ./
          # cname: money.thomasrosen.me
          branch: deployment
      - name: run deploy commands on uberspace
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: cd ~/money/ && git checkout deployment && git pull && yarn && supervisorctl restart money;
          host: giclas.uberspace.de
          username: qiekub
          password: ${{ secrets.UBERSPACE_PASSWORD_QIEKUB }}
